version: '3.8'
services:
  bucket-service:
    build: .
    command: npm run start
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - custom-my-network
  pricing-worker:
    build: .
    command: npm run start-worker
    volumes:
      - .:/app
    depends_on:
      - redis
      - bucket-service
    networks:
      - custom-my-network
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - custom-my-network

networks:
  custom-my-network:
    name: my-network
    driver: bridge